version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3080:3000'
    depends_on:
      - mongo
    environment:
      BLOCKEXPLORERURL: ${APP_ROOT_URL:-http://localhost}
      # MONGO_URL: mongodb://mongo:27017/meteor
      MONGO_URL: mongodb://localhost:27017/meteor
      PORT: 3000
    volumes:
      - ./settings-files/landslide-simd.json:/config/settings.json:ro
    network_mode: "host"

  mongo:
    image: mongo:latest
    command:
      - --storageEngine=wiredTiger
    volumes:
      - data:/data/db
    network_mode: "host"

volumes:
  data:
